# Uncomment this line to define a global platform for your project
platform :ios, '11.0'
source 'https://cdn.cocoapods.org/'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  pod 'CourierCore', '0.0.7', :modular_headers => true
  pod 'CourierMQTT', '0.0.7', :modular_headers => true
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|

        if target.name == "CourierCore" || target.name == "CourierMQTT"
            if config.name == 'Debug'
                config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] = '$(inherited) DEBUG INTEGRATION'
            else
                if config.name == 'Profile'
                    config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] = '$(inherited)' + ' ALPHA ' + config.name.upcase
                else
                    config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] = '$(inherited)' + ' ' + config.name.upcase
                end
            end
        end
    end
  end
end

