name: courier_protobuf
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  courier_dart_sdk: 0.0.9
  protobuf: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: